import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: {
    default: 'Learning NextJS',
    template: '%s | NextJs'
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
          <header style={{backgroundColor: '#07b4e8', padding: '1rem'}}>
             Main Heading
          </header>

          {children}

          <footer style={{backgroundColor: "#a4e2f5",  padding: "1rem"}}>
            Footer section
          </footer>
      </body>
    </html>
  );
}
